### ISSUE TITLE
Didn't tag audio

### ISSUE THREAD

**Issue by lemmensaxel** [Jense5/Pulse#2]
{"level":"info","message":"WINDW: Called initializeWindows","timestamp":"2015-09-22T13:22:49.891Z"}
{"level":"info","message":"MAIN/VIEWS.JS: Called initializeViews()","timestamp":"2015-09-22T13:22:49.894Z"}
{"level":"info","message":"MAIN/VIEWS.JS: Called initializeButtons()","timestamp":"2015-09-22T13:22:49.894Z"}
{"level":"info","message":"VIEWS: Called initializeMenuBar()","timestamp":"2015-09-22T13:22:49.895Z"}
{"level":"info","message":"MAIN/VIEWS.JS: Called openIssueReporterButton()","timestamp":"2015-09-22T13:22:52.724Z"}
{"level":"info","message":"MAIN/VIEW.JS: Called openIssueReportWindow()","timestamp":"2015-09-22T13:22:52.724Z"}
{"level":"info","message":"MAIN/VIEW.JS: Creating new issueReportWindow","timestamp":"2015-09-22T13:22:52.725Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Called initializeWindows()","timestamp":"2015-09-22T13:22:53.190Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Called initializeButtons()","timestamp":"2015-09-22T13:22:53.195Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Called windowClose()","timestamp":"2015-09-22T13:23:10.547Z"}
{"level":"info","message":"MAIN/VIEW.JS: Closed issueReportWindow","timestamp":"2015-09-22T13:23:10.557Z"}
{"level":"info","message":"MAIN/VIEWS.JS: Called openTutorialButton()","timestamp":"2015-09-22T13:23:12.028Z"}
{"level":"info","message":"MAIN/VIEW.JS: Called openTutorialWindow()","timestamp":"2015-09-22T13:23:12.028Z"}
{"level":"info","message":"MAIN/VIEW.JS: Creating new tutorialWindow","timestamp":"2015-09-22T13:23:12.029Z"}
{"level":"info","message":"TUTORIAL/TUTORIAL.JS: Called initializeWindows()","timestamp":"2015-09-22T13:23:12.386Z"}
{"level":"info","message":"TUTORIAL/TUTORIAL.JS: Called closeWindow()","timestamp":"2015-09-22T13:23:32.323Z"}
{"level":"info","message":"MAIN/VIEW.JS: Closed tutorialWindow","timestamp":"2015-09-22T13:23:32.330Z"}
{"level":"info","message":"MAIN/VIEW.JS: Called showSearchView()","timestamp":"2015-09-22T13:24:18.978Z"}
{"level":"info","message":"MAIN/VIEW.JS: Called hideSearchView()","timestamp":"2015-09-22T13:24:20.521Z"}
{"level":"info","message":"MAIN/VIEWS.JS: Called downloadButton()","timestamp":"2015-09-22T13:24:22.640Z"}
{"level":"info","message":"MAIN/CORE.JS: Called startDownload","timestamp":"2015-09-22T13:24:22.641Z"}
{"level":"info","message":"MAIN/CORE.JS: Called askForPath","timestamp":"2015-09-22T13:24:22.641Z"}
{"level":"info","message":"MAIN/CORE.JS: Received path: /Users/Axel/Desktop","timestamp":"2015-09-22T13:24:26.619Z"}
{"level":"info","message":"MAIN/VIEW.JS: called showDownloadViews()","timestamp":"2015-09-22T13:24:26.619Z"}
{"level":"info","message":"MAIN/CORE.JS: Called executeDownloadCommand","timestamp":"2015-09-22T13:24:26.620Z"}
{"level":"debug","message":"MAIN/CORE.JS: Starting Youtube-dl with command: cd /Users/Axel/Desktop && /Applications/Pulse.app/Contents/Resources/app/main/../bin/youtube-dl -x --audio-format mp3 -i --ffmpeg-location /Applications/Pulse.app/Contents/Resources/app/main/../bin/ffmpeg https://www.youtube.com/watch?v=MysKegBRtaA","timestamp":"2015-09-22T13:24:26.620Z"}
{"level":"info","message":"MAIN/CORE.JS: Youtube-dl finished","timestamp":"2015-09-22T13:24:33.356Z"}
{"level":"debug","message":"MAIN/CORE.JS: Youtube-dl finished with stdout: [youtube] MysKegBRtaA: Downloading webpage\n[youtube] MysKegBRtaA: Downloading video info webpage\n[youtube] MysKegBRtaA: Extracting video information\n[youtube] MysKegBRtaA: Downloading js player new-en_US-vflSnomqH\n[youtube] MysKegBRtaA: Downloading DASH manifest\n[download] Destination: Zara Larsson - Lush Life (Audio)-MysKegBRtaA.webm\n\r[download]   0.0% of 3.33MiB at 102.44KiB/s ETA 00:33\r[download]   0.1% of 3.33MiB at 299.17KiB/s ETA 00:11\r[download]   0.2% of 3.33MiB at 685.54KiB/s ETA 00:04\r[download]   0.4% of 3.33MiB at  1.41MiB/s ETA 00:02\r[download]   0.9% of 3.33MiB at  2.45MiB/s ETA 00:01\r[download]   1.8% of 3.33MiB at  2.72MiB/s ETA 00:01\r[download]   3.7% of 3.33MiB at  3.88MiB/s ETA 00:00\r[download]   7.5% of 3.33MiB at  5.68MiB/s ETA 00:00\r[download]  15.0% of 3.33MiB at  8.11MiB/s ETA 00:00\r[download]  30.0% of 3.33MiB at 11.95MiB/s ETA 00:00\r[download]  60.1% of 3.33MiB at 14.36MiB/s ETA 00:00\r[download] 100.0% of 3.33MiB at 15.95MiB/s ETA 00:00\r[download] 100% of 3.33MiB in 00:00\n[ffmpeg] Destination: Zara Larsson - Lush Life (Audio)-MysKegBRtaA.mp3\nDeleting original file Zara Larsson - Lush Life (Audio)-MysKegBRtaA.webm (pass -k to keep)\n","timestamp":"2015-09-22T13:24:33.357Z"}
{"level":"info","message":"MAIN/CORE.JS: Called executeMinoCommand()","timestamp":"2015-09-22T13:24:33.357Z"}
{"level":"debug","message":"MAIN/CORE.JS: Mino's command: python /Applications/Pulse.app/Contents/Resources/app/main/../scripts/mino.py /Users/Axel/Desktop","timestamp":"2015-09-22T13:24:33.357Z"}
{"level":"info","message":"MAIN/CORE.JS: Finished Mino script","timestamp":"2015-09-22T13:24:33.784Z"}
{"level":"error","message":"MAIN/CORE.JS: Mino stopped with error: Error: stdout maxBuffer exceeded.","timestamp":"2015-09-22T13:24:33.785Z"}
{"level":"info","message":"MAIN/VIEW.JS: called hideDownloadViews()","timestamp":"2015-09-22T13:24:33.785Z"}
{"level":"info","message":"MAIN/VIEWS.JS: Called openIssueReporterButton()","timestamp":"2015-09-22T13:24:53.553Z"}
{"level":"info","message":"MAIN/VIEW.JS: Called openIssueReportWindow()","timestamp":"2015-09-22T13:24:53.553Z"}
{"level":"info","message":"MAIN/VIEW.JS: Creating new issueReportWindow","timestamp":"2015-09-22T13:24:53.553Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Called initializeWindows()","timestamp":"2015-09-22T13:24:53.911Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Called initializeButtons()","timestamp":"2015-09-22T13:24:53.914Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Called buttonExport()","timestamp":"2015-09-22T13:24:54.984Z"}
{"level":"debug","message":"ISSUE/ISSUE.JS: Received path: /Users/Axel/Desktop","timestamp":"2015-09-22T13:24:57.207Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Successfully exported crashfile","timestamp":"2015-09-22T13:24:57.209Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Called windowClose()","timestamp":"2015-09-22T13:25:43.503Z"}
{"level":"info","message":"MAIN/VIEW.JS: Closed issueReportWindow","timestamp":"2015-09-22T13:25:43.607Z"}
{"level":"info","message":"MAIN/VIEW.JS: Called showSearchView()","timestamp":"2015-09-22T13:26:17.436Z"}
{"level":"info","message":"MAIN/VIEW.JS: Called hideSearchView()","timestamp":"2015-09-22T13:26:17.967Z"}
{"level":"info","message":"MAIN/VIEW.JS: Called showSearchView()","timestamp":"2015-09-22T13:26:27.841Z"}
{"level":"info","message":"MAIN/VIEW.JS: Called hideSearchView()","timestamp":"2015-09-22T13:26:28.139Z"}
{"level":"info","message":"MAIN/VIEWS.JS: Called downloadButton()","timestamp":"2015-09-22T13:26:30.927Z"}
{"level":"info","message":"MAIN/CORE.JS: Called startDownload","timestamp":"2015-09-22T13:26:30.928Z"}
{"level":"info","message":"MAIN/CORE.JS: Called askForPath","timestamp":"2015-09-22T13:26:30.928Z"}
{"level":"info","message":"MAIN/CORE.JS: Received path: /Users/Axel/Desktop","timestamp":"2015-09-22T13:26:32.885Z"}
{"level":"info","message":"MAIN/VIEW.JS: called showDownloadViews()","timestamp":"2015-09-22T13:26:32.886Z"}
{"level":"info","message":"MAIN/CORE.JS: Called executeDownloadCommand","timestamp":"2015-09-22T13:26:32.886Z"}
{"level":"debug","message":"MAIN/CORE.JS: Starting Youtube-dl with command: cd /Users/Axel/Desktop && /Applications/Pulse.app/Contents/Resources/app/main/../bin/youtube-dl -x --audio-format mp3 -i --ffmpeg-location /Applications/Pulse.app/Contents/Resources/app/main/../bin/ffmpeg https://www.youtube.com/watch?v=MysKegBRtaA","timestamp":"2015-09-22T13:26:32.886Z"}
{"level":"info","message":"MAIN/CORE.JS: Youtube-dl finished","timestamp":"2015-09-22T13:26:39.474Z"}
{"level":"debug","message":"MAIN/CORE.JS: Youtube-dl finished with stdout: [youtube] MysKegBRtaA: Downloading webpage\n[youtube] MysKegBRtaA: Downloading video info webpage\n[youtube] MysKegBRtaA: Extracting video information\n[youtube] MysKegBRtaA: Downloading DASH manifest\n[download] Destination: Zara Larsson - Lush Life (Audio)-MysKegBRtaA.webm\n\r[download]   0.0% of 3.33MiB at 130.36KiB/s ETA 00:26\r[download]   0.1% of 3.33MiB at 376.13KiB/s ETA 00:09\r[download]   0.2% of 3.33MiB at 855.63KiB/s ETA 00:03\r[download]   0.4% of 3.33MiB at  1.75MiB/s ETA 00:01\r[download]   0.9% of 3.33MiB at  2.09MiB/s ETA 00:01\r[download]   1.8% of 3.33MiB at  3.34MiB/s ETA 00:00\r[download]   3.7% of 3.33MiB at  4.66MiB/s ETA 00:00\r[download]   7.5% of 3.33MiB at  6.67MiB/s ETA 00:00\r[download]  15.0% of 3.33MiB at  9.59MiB/s ETA 00:00\r[download]  30.0% of 3.33MiB at 13.39MiB/s ETA 00:00\r[download]  60.1% of 3.33MiB at 17.28MiB/s ETA 00:00\r[download] 100.0% of 3.33MiB at 19.13MiB/s ETA 00:00\r[download] 100% of 3.33MiB in 00:00\n[ffmpeg] Destination: Zara Larsson - Lush Life (Audio)-MysKegBRtaA.mp3\nDeleting original file Zara Larsson - Lush Life (Audio)-MysKegBRtaA.webm (pass -k to keep)\n","timestamp":"2015-09-22T13:26:39.475Z"}
{"level":"info","message":"MAIN/CORE.JS: Called executeMinoCommand()","timestamp":"2015-09-22T13:26:39.475Z"}
{"level":"debug","message":"MAIN/CORE.JS: Mino's command: python /Applications/Pulse.app/Contents/Resources/app/main/../scripts/mino.py /Users/Axel/Desktop","timestamp":"2015-09-22T13:26:39.475Z"}
{"level":"info","message":"MAIN/CORE.JS: Finished Mino script","timestamp":"2015-09-22T13:26:39.678Z"}
{"level":"error","message":"MAIN/CORE.JS: Mino stopped with error: Error: stdout maxBuffer exceeded.","timestamp":"2015-09-22T13:26:39.679Z"}
{"level":"info","message":"MAIN/VIEW.JS: called hideDownloadViews()","timestamp":"2015-09-22T13:26:39.679Z"}
{"level":"info","message":"MAIN/VIEWS.JS: Called openIssueReporterButton()","timestamp":"2015-09-22T13:27:02.700Z"}
{"level":"info","message":"MAIN/VIEW.JS: Called openIssueReportWindow()","timestamp":"2015-09-22T13:27:02.700Z"}
{"level":"info","message":"MAIN/VIEW.JS: Creating new issueReportWindow","timestamp":"2015-09-22T13:27:02.700Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Called initializeWindows()","timestamp":"2015-09-22T13:27:03.100Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Called initializeButtons()","timestamp":"2015-09-22T13:27:03.104Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Called buttonExport()","timestamp":"2015-09-22T13:27:04.493Z"}
{"level":"debug","message":"ISSUE/ISSUE.JS: Received path: /Users/Axel/Desktop","timestamp":"2015-09-22T13:27:06.190Z"}
{"level":"info","message":"ISSUE/ISSUE.JS: Successfully exported crashfile","timestamp":"2015-09-22T13:27:06.192Z"}

**Comment by Jense5** [comment]
I can't know exactly whats wrong because I have to know what's on your desktop. I fixed it for now by creating a new download folder in the destination folder, named "pulse". This should fix this issue in most cases. I will ship it with bèta 2 or you can run it from the source.
